#!/bin/bash
git clone https://github.com/lxqt/lxqt.wiki.git tmp/lxqt
git clone https://github.com/lxqt/pcmanfm-qt.wiki.git tmp/pcmanfm-qt
#mv -v tmp/lxqt/*.md docs/lxqt.wiki
sed -i '7,26d' tmp/pcmanfm-qt/Home.md #removal of the table
sed -i '1d' tmp/pcmanfm-qt/Home.md
mv -v tmp/pcmanfm-qt/Home.md docs/lxqt.wiki/Pcmanfm-qt.md
mv -v tmp/pcmanfm-qt/*.md docs/lxqt.wiki
# convert [!NOTE] to material syntax
sed -i -E ':a;N;$!ba;s/> \[!NOTE]\n> (.*)/!!! note\n     \1/'  docs/lxqt.wiki/*.md
rm -rf tmp/*
