#!/bin/bash

#git clone https://github.com/lxqt/lxqt.wiki.git tmp/lxqt
git clone https://github.com/stefonarch/pcmanfm-qt.wiki.git tmp/pcmanfm-qt

# import:
# mv -v tmp/lxqt/*.md docs/lxqt.wiki
# sed -i '7,26d' tmp/pcmanfm-qt/Home.md #removal of the table
# sed -i '1d' tmp/pcmanfm-qt/Home.md
# mv -v tmp/pcmanfm-qt/Home.md docs/lxqt.wiki/Pcmanfm-qt.md
# mv -v tmp/pcmanfm-qt/*.md docs/lxqt.wiki
# convert [!NOTE] to material syntax (only needed when importing)
# sed -i -E ':a;N;$!ba;s/> \[!NOTE]\n> (.*)/!!! note\n     \1/'  docs/lxqt.wiki/*.md
# rm -rf tmp/*

# export to old github wiki

#cp -v docs/lxqt.wiki/*.md tmp/lxqt.wiki
cp -v docs/lxqt.wiki/custom_actions.md tmp/pcmanfm-qt/
cp -v docs/lxqt.wiki/Pcmanfm-qt.md  tmp/pcmanfm-qt/Home.md
cd tmp/pcmanfm-qt
git add . && git commit -m "Commit from new wiki" && git push  #add identifier?
cd ../..
rm -rf tmp/*


